---
title: 固件全收集
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  wiki:
    title: Wiki
    output: true
    permalink: "/wiki/:path/"
baseurl: 
url: https://getrom.github.io
date_format: ordinal
subtitle: 
description: 
keywords: N1固件, Webpad固件, YYF, Rush, N1旁路由, K2P固件, 荒野无灯
encoding: utf-8
side_bar_repo_limit: 5
repository: getrom/getrom.github.io
cdn:
  jsdelivr:
    enabled: true
components:
  share:
    enabled: false
  busuanzi:
    enabled: true
    start_date: 2020-05-03 00:00:00.000000000 Z
compress_html:
  clippings: all
  comments:
  - "<!--"
  - "-->"
word_count:
  enabled: true
highlight_theme: github
author: 老白
organization: 
organization_url: 
github_username: GetROM
location: Beijing, China
email: getrom@gmail.com
navs:
- href: "/"
  label: 首页
- href: "/categories/"
  label: 分类
- href: "/wiki/"
  label: 维基
- href: "/links/"
  label: 链接
- href: "/about/"
  label: 关于
subscribe_rss: "/feed.xml"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: "/:year/:month/:day/:title/"
plugins:
- jekyll-github-metadata
- rouge
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jemoji
comments_provider: gitalk
disqus:
  username: 
gitment:
  owner: mzlogin
  repo: blog-comments
  oauth:
    client_id: d2e1cbbd298958076462
    client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
gitalk:
  owner: mzlogin
  repo: blog-comments
  clientID: d2e1cbbd298958076462
  clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
lazy_load_disqus: false
simple_jekyll_search:
  fulltext: false
  limit: 10
google:
  analytics_id: UA-80669434-1
  adsense:
    footer: false
    sidebar: false
    content_header: false
    content_footer: false
